-sverilog
+incdir+${AIDC_LITE_HOME}/interface/sverilog
${AIDC_LITE_HOME}/interface/sverilog/AHB2_INTF.sv
${AIDC_LITE_HOME}/interface/sverilog/APB_INTF.sv
+incdir+${AIDC_LITE_HOME}/design/sverilog
${AIDC_LITE_HOME}/design/sverilog/AIDC_LITE_COMP_CFG.sv
${AIDC_LITE_HOME}/design/sverilog/AIDC_LITE_COMP_ENGINE.sv
${AIDC_LITE_HOME}/design/sverilog/AIDC_LITE_COMP_TOP.sv
${AIDC_LITE_HOME}/design/sverilog/AIDC_LITE_COMP_TOP_WRAPPER.sv
